# vich_uploader:
#     db_driver: orm
#     metadata:
#         type: attribute
#     mappings:
#         fiches:
#             uri_prefix: /files/fiches
#             upload_destination: "%kernel.project_dir%/public/files/fiches"
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        fiches:
            uri_prefix: /images/fiches
            upload_destination: "%kernel.project_dir%/public/files/fiches"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer